name: assignment
description: A financial management app for Assign ur Assignment business.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0  # For date formatting
  sqflite: ^2.2.8+4  # For local database (SQLite)
  path_provider: ^2.1.2  # To get file system paths

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
